### ISSUE TITLE
Adding your 'language-igor' to GitHub linguist for syntax highlighting on GitHub

### ISSUE THREAD

**Issue by ankit7540** [shanemcmahon/language-igor#1]
Hello,
May I start the process to use your repository by GitHub for automatic language highlighting ?
Specifically, to the [https://github.com/github/linguist](linguist) repository used by GitHub.  
Also check this : [https://github.com/github/linguist/blob/master/CONTRIBUTING.md](url)

**Comment by t-b** [comment]
@ankit7540 In case @shanemcmahon is not using this repo anymore. Maybe you can fork the project and get it included into linguist?

**Comment by shanemcmahon** [comment]
I'll work on submitting a pull request to linguist over the next few days. The read me suggests they prefer that languages are used by "several hundred" projects on github before adding support for a language, so it's possible they won't be interested.

**Comment by t-b** [comment]
@shanemcmahon It was already part of linguist before, see https://github.com/github/linguist/commit/bc01f8b25f4deb37dee05be3e8eb897507a749a7. But then they switched highilightning engines. So I think the relevance discussion can be won.

**Comment by ankit7540** [comment]
@shanemcmahon and @t-b  Thanks for the initiatives. :-)
